import Link from 'next/link';
import { MdArrowBack, MdFavoriteBorder } from 'react-icons/md';
import { tv } from 'tailwind-variants';

import { Tabs } from '@/app/_components/tabs';

export const metadata = {
  title: 'レシピ詳細',
  description: 'Generated by create next app',
};

const recipeTab = tv({
  slots: {
    main: 'm-auto max-w-[400px]', // TODO: ここでmax-wを指定せずサイドバーと合わせて指定した方がよさそう
    imageArea: 'aspect-square bg-red-200',
    back: 'absolute left-5 top-5 h-8 w-8',
    backIcon: 'h-8 w-8 text-white',
    fav: 'absolute bottom-0 right-0 m-2 h-[3.75rem] w-[3.75rem] rounded-full bg-[#908E96]',
    favArea: 'absolute left-3 top-[0.875rem] h-8 w-8',
    favIcon: 'h-9 w-9 text-white',
    recipeName: 'm-4 text-[28px] font-bold',
  },
});

const { main, imageArea, back, backIcon, fav, favArea, favIcon, recipeName } =
  recipeTab();

// いったんjsonplaceholderからデータ取得
interface Post {
  userId: number;
  id: number;
  title: string;
  body: string;
}

// generateStaticParamsを使う
// https://nextjs.org/docs/app/api-reference/functions/generate-static-params
export async function generateStaticParams() {
  // TODO: レシピ詳細APIからレシピIDを取得する
  const posts: Post[] = await fetch(
    'https://jsonplaceholder.typicode.com/posts'
  ).then((res) => res.json());

  const ids = posts.map((post) => ({
    recipeId: String(post.id),
  }));

  return [...ids];
}

export default async function Layout({
  params,
  children,
}: {
  params: { recipeId: string };
  children: React.ReactNode;
}) {
  const { recipeId } = params;

  // いったんjsonplaceholderからデータ取得
  const data: Post[] = await fetch(
    `https://jsonplaceholder.typicode.com/todos?id=${recipeId}`
  ).then((res) => res.json());

  const tabs = [
    {
      path: `/recipe/${recipeId}`,
      tabText: '作り方',
    },
    {
      path: `/recipe/${recipeId}/ingredients`,
      tabText: '材料',
    },
  ];

  return (
    <main className={main()}>
      {/* 料理画像 */}
      <div className='relative'>
        <div className={imageArea()} />
        <Link href='/search/recipe' className={back()}>
          <MdArrowBack className={backIcon()} />
        </Link>
        <div className={fav()}>
          <div className={favArea()}>
            {/* TODO: Favo/Unfavoの切り替え */}
            <MdFavoriteBorder className={favIcon()} />
          </div>
        </div>
      </div>
      {/* 料理名、説明文 */}
      <div>
        <p className={recipeName()}>{data[0].title}</p>
        <p className='m-4'>
          はじめてでも失敗なく作れるような、鶏肉や玉ねぎを具とした基本的なマカロニグラタンのレシピです。
          ソースと具材炒めを別器具で行うレシピも多いですが、グラタンの具を炒めたフライパンの中で、そのままホワイトソースを仕上げる手軽な作り方にしています。ぜひお試しください。
        </p>
        {/* お気に入り */}
        <div className='m-4 flex gap-2'>
          <p className='font-bold'>789</p>
          <p className='text-[#6F6E77]'>お気に入り</p>
        </div>
      </div>
      <Tabs tabs={tabs} />
      {children}
    </main>
  );
}
